### ISSUE TITLE
Backward chaining

### ISSUE THREAD

**Issue by daya** [lorenzosinisi/retex#13]
@lorenzosinisi Does this library support Backward chaining execution method or just Forward chaining? If not supported then what would it take to support Backward chaining? I know some Elixir and I am learning RETE algorithm.

**Comment by lorenzosinisi** [comment]
Hi @daya yes sure, backward chaining execution can be achived by using negative node types that infer the non-existance of each WMEs needed for the final goal. One rule (end goal) will be fired when all negative node types are proved false.

Does that make sense?

**Comment by daya** [comment]
> Does that make sense?

Nah it doesn't. May be the explanation is too much reliant on terminologies of this library and I am just coming up to speed with it. Is there a test case I can look at to better understand this?
